name: Staging PR Teardown
on:
  pull_request:
    branches: [dev]
    types: [closed]
    paths-ignore:
      - "**.md"
env:
  PR_REPO_NAME: staging-pr-${{ github.event.pull_request.node_id }}
jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete repository for temporary deployment
        uses: dcyoung/ga-delete-git-repo@v1.0.0
        with:
          name: dcyoung/${{ env.PR_REPO_NAME }}
          access-token: ${{ secrets.PAT }}
