name: Staging PR Teardown
on:
  pull_request:
    branches: [dev]
    types: [closed]
    paths-ignore:
      # - ".github/workflows/**"
      - "**.md"

env:
  PR_REPO_NAME: pr-${{ github.event.pull_request.node_id }}

jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Delete repository for temporary deployment
        uses: ./actions/delete-git-repo
        with:
          name: octobay/${{ env.PR_REPO_NAME }}
          access-token: ${{ secrets.PAT }}
